name: Points League 2024 Update

on:
  schedule:
    - cron "0 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

  - name: Setup Python Version
    uses: actions/setup-python@v2
    with:
      python-version: 3.8

  - name: Install Python dependencies
    uses: py-actions/py-denepdency-install@v2
    with:
      path: "requirements.txt"

  - name: Execute Python script
    run: python points_league_2024.py

  - name: Commit files
    run:
      git config --local user.name jseibert575
      git config --local user.email "jseibert575@gmail.com"
      git add "pointsleague_2024.csv"
      git add "full_points_table_2024.csv"
      git commit -m "Updating points league data $(date)"
      git push origin main
    env:
      REPO_KEY: ${{secrets.GITHUB_TOKEN}}$
      username: github-actions
  
