name: Update Points League Data

on:
  schedule:
    - cron: "5 12 * * *"

  workflow_dispatch:

env:
  SEASON: "2026"

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Execute Python script
        env:
          WEBSHARE_PROXY: ${{ secrets.WEBSHARE_PROXY }}
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 60
          command: uv run points_league.py

      - name: Commit files
        run: |
          git config --local user.name jseibert575
          git config --local user.email "jseibert575@gmail.com"
          git add seasons/$SEASON/data/
          git diff --cached --quiet || git commit -m "Updating data $(date)"
          git push
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
